name: Add version

on:
  workflow_dispatch:
    inputs:
      version:
          description: 'Please enter the version, eg 0.0.1+26.'
          required: true
          type: string

jobs:
  version:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PICGUARD_HOMEBREW }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Update version
        shell: bash
        run: ruby scripts/release.rb "$VERSION"
        env:
          VERSION: ${{ github.event.inputs.version }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: ${{ github.event.inputs.version }}"
          commit_options: '--no-verify --signoff'
          commit_user_name: kjxbyz
          commit_user_email: kjxbyz888@outlook.com
          commit_author: kjxbyz <kjxbyz888@outlook.com>
          add_options: '-A'
          push_options: '--force'
